### ISSUE TITLE
Add type hints to Enum attributes

### ISSUE THREAD

**Issue by nh916** [C-Accel-CRIPT/Python-SDK#97]
## Description

add type hints when time is available

```python
class SearchModes(Enum):
    NODE_TYPE = ""
    EXACT_NAME = "exact_name"
    CONTAINS_NAME = "contains_name"
    UUID = "uuid"
```

**Comment by Abraham12611** [comment]
Hello there. I'm new to contributing to open source projects and would love to contribute to this project. So please how may I be of help?

**Comment by nh916** [comment]
@Abraham12611 feel free to pick an issue that you would like to help with and knock it out.

Documentation could always use an upgrade and it will teach you about our software as well.

this is a good first issue to knock out as well!
https://github.com/C-Accel-CRIPT/Python-SDK/issues/119

**Comment by nh916** [comment]
done! ✅
